### ISSUE TITLE
Sidebar: problem on device

### ISSUE THREAD

**Issue by slanska** [webix-hub/components#8]
Minimized sidebar not working on device at all! Check your own sample page on device (http://webix-hub.github.io/components/sidebar/sample.html), minimize sidebar, try to touch on icons.

**Comment by Maria-Staskova** [comment]
The issue is fixed

**Comment by slanska** [comment]
I just tried the same page (http://webix-hub.github.io/components/sidebar/sample.html) on iPad Mini. In minimized state, buttons do no react  on touch (last button "Documentation", without submenu, works, though). Seems still broken.
 


    On Wednesday, November 25, 2015 6:55 AM, Maria-Staskova <notifications@github.com> wrote:
 

 The issue is fixed—

**Comment by mkozhukh** [comment]
Please check the issue once more. I have checked the same link from my side, and it works correctly on iPad. Maybe it some kind of cache on your end. 

If issue still occurs, can you share the iOs version on the problematic device.

**Comment by slanska** [comment]
yep, it is working perfectly now. Thanks, Masha!
 


    On Monday, December 7, 2015 7:01 AM, Maksim Kozhukh <notifications@github.com> wrote:
 

 Please check the issue once more. I have checked the same link from my side, and it works correctly on iPad. Maybe it some kind of cache on your end. If issue still occurs, can you share the iOs version on the problematic device. —
